### ISSUE TITLE
A random sentence field is showing up in different words containing a random string.

### ISSUE THREAD

**Issue by ghost** [Lyroxide/yomitan-ko-dic#1]
![image](https://github.com/Lyroxide/yomitan-ko-dic/assets/103891807/c435a434-d06a-42fb-9462-483e8ce7dcce)

Dict - KO-EN

**Comment by Lyroxide** [comment]
It is not random. This is shown even in the original website. It shows you how to grammatically use the word.

**Comment by ghost** [comment]
Oh, okay. Is there any way to remove these two using CSS?

![image](https://github.com/Lyroxide/yomitan-ko-dic/assets/103891807/cbf9e34a-2487-4bfe-a25d-05faf993e4a0)

And, also what about anki? is there any way to remove it from anki rather than only from the dictionary appearance?

**Comment by Lyroxide** [comment]
Tried to experiment with this but unfortunately even if you can hide it, you cannot remove it in your Anki card. However, I believe it's good information to have.
