### ISSUE TITLE
CC100 for Korean can't be imported if CC100 for Japanese is also installed

### ISSUE THREAD

**Issue by BlackJack-HK** [Lyroxide/yomitan-ko-dic#3]
It seems Yomitan considers them as the same dictionary:
![image](https://github.com/user-attachments/assets/e32cd086-6579-4038-9a03-c733af0605c9)
I'm using Yomitan 24.7.24.0

**Comment by Lyroxide** [comment]
Thanks for letting me know. It's now fixed.
