### ISSUE TITLE
Terms containing bracketed optional parts should be duplicated

### ISSUE THREAD

**Issue by peldas** [Lyroxide/yomitan-ko-dic#4]
Entries like `뜸 들이다`/`뜸을 들이다` do not appear when scanned as the relevant headword is actually `뜸(을) 들이다`. It would be better to handle these brackets and create a separate entry for every permutation of optional parts (otherwise these entries are completely useless). Screenshot included is from my hanja fork of these dictionaries but it's the same thing for this entry.
![image](https://github.com/user-attachments/assets/8cb5fc37-0349-498a-a005-6a04853f9084)

**Comment by Lyroxide** [comment]
Fixed. Thanks for letting me know.
